backend:
  name: github
  repo: sulenchy/school-website
  branch: main

media_folder: public/assets/images/uploads
public_folder: assets/images/uploads

collections:
  - name: "galleries"
    label: "Gallery"
    folder: "_contents/gallery"
    create: true
    delete: true
    extension: "json"
    format: "json-frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "galleries" }
      - { label: "Alt", name: "alt", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Src", name: "src", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }
  - name: "news"
    label: "News"
    folder: "_contents/news"
    create: true
    delete: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "news" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Src", name: "src", widget: "image" }
      - { label: "Content", name: "content", widget: "markdown" }

  - name: "posts"
    label: "Posts"
    folder: "_content/posts/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: Author
        name: "author"
        widget: relation
        collection: "meta"
        file: "authors"
        searchFields:
          - "authors.*.name"
        displayFields:
          - "authors.*.name"
        valueField: "authors.*.slug"
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: "Body"
        name: "body"
        widget: "markdown"