backend:
  name: github
  repo: sulenchy/school-website
  branch: main

media_folder: public/assets/images/uploads
public_folder: assets/images/uploads

collections:
  - name: "galleries"
    label: "Gallery"
    folder: "_contents/gallery"
    create: true
    delete: true
    extension: "json"
    format: "json-frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "galleries" }
      - { label: "Alt", name: "alt", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Src", name: "src", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }
  - name: "news"
    label: "News"
    folder: "_contents/news"
    create: true
    delete: true
    extension: "json"
    format: "json-frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "news" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Src", name: "src", widget: "image" }
      - { label: "Content", name: "content", widget: "markdown" }
